### ISSUE TITLE
In the rounds list, the score of the rounds is 10000%

### ISSUE THREAD

**Issue by MelanieApplincourt** [MelanieApplincourt/REPO_UZ_1234987#102]
![screen shot 2016-04-25 at 18 28 51](https://cloud.githubusercontent.com/assets/2649355/14790892/aa47a512-0b13-11e6-9eeb-54b25a622548.png)

**Comment by Justinuz** [comment]
DOne

**Comment by MelanieApplincourt** [comment]
Finally, it's ok ;-)

**Comment by MelanieApplincourt** [comment]
Finally it's not OK, I still have a third place where it's not correct:
![Uploading Screen Shot 2016-04-28 at 23.23.26.png…]()

**Comment by Justinuz** [comment]
Finally it's done

**Comment by MelanieApplincourt** [comment]
I hope it will be the last place. It's good !
