### ISSUE TITLE
Cannot change the sample file template

### ISSUE THREAD

**Issue by GuillaumeGolinvaux** [MelanieApplincourt/REPO_UZ_1234987#169]
Dev server.

The button to change the sample file in the flux configuration does not work:
![image](https://cloud.githubusercontent.com/assets/18420928/15354766/820700a0-1cef-11e6-90a7-9aa5c7f74aab.png)

**Comment by Justinuz** [comment]
DONE :octocat:

**Comment by GuillaumeGolinvaux** [comment]
![image](https://cloud.githubusercontent.com/assets/18420928/15702540/e0ec2a40-27e0-11e6-990a-7cdfbe1380b6.png)

The issue is still here, it depends on the format of the window:

![image](https://cloud.githubusercontent.com/assets/18420928/15702594/2fca53c6-27e1-11e6-86c8-821940fd0390.png)

**Comment by GuillaumeGolinvaux** [comment]
Ok
